Added  work_section
coker2019/Coker_Portfolio pull request #3
Opened 2023-02-18 21:14 UTC by coker2019

In the Works section, I use CSS Grid and Flexbox in the main container that contains all of the cards so that work is done.

2023-02-18 21:32 UTC, jerryowusu requested changes
Hi @coker2019 , 

Good job so far!
Your project is looking fantastic so far :star_struck: 

However, there are few changes you need to make in order to move on to the next level :sunglasses:

![Screenshot from 2023-02-18 21-33-13](https://user-images.githubusercontent.com/65233860/219900407-aa372663-a901-4b8b-9728-22ac48e623dd.png)


## Highlights
No linter errors :heavy_check_mark: 
Good job so far :heavy_check_mark: 

## Required Changes ♻️

- [ ] In this milestone you are suppose to add the about me section but it is not present here. Kindly add it and make sure the design conforms to the actual figma design :pray: 

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-18 21:32 UTC, jerryowusu commented on index.html
> +        <h3 class="daily_text">A daily selection of privately <br> personalized reads; no accounts or <br> sign-ups required.</h3>
Since this is a paragraph kindly consider using the p tag instead of the h3 tag. :+1:

2023-02-18 21:32 UTC, jerryowusu commented on index.html
> +  </section>
According to the design for this template, your work section should include four individual project cards aligned with display: grid. However, I can only see one project card. Kindly check and make these changes to conform to the figma design. :pray:

2023-02-22 16:38 UTC, Abenezer-Tilahun requested changes
Hi @coker2019  , 

Great job for implemented  the suggested changes , but there are some changes that need to be implemented in order to proceed to the next project 👍

## Highlights 👏🏻

✔️ No Linters error
✔️ You used correct Git Hub-Flow.
✔️ Good commit messages
✔️ Professional READEME 


![almost](https://user-images.githubusercontent.com/65860678/170491251-b1add8ba-b18f-4648-a893-20e510d957fd.gif)

## Required Changes ♻️
_Check the comments below the review._

- [x] Good Job for using the New README file but I recommend you to customize the README File according the current project , because some of the section description are from the previous project.  

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-22 16:38 UTC, Abenezer-Tilahun commented on index.html
> +          <h1 class="tonic-text">Tonic</h1>
- [x] Kindly I recommend you to use a header tag `hx(h2)` for the the project title (e.g., "Tonic") instead of using `h1` tag for the purpose of search and optimization there must be only one `h1`   tag for your project.

2023-02-22 16:38 UTC, Abenezer-Tilahun commented on index.html
> +              <h1 class="text_project">See Project</h1>
- [x] Kindly I recommend you to use only `button` tag for the See Project , please remove the `h1` tag for all of the button tag.

2023-02-22 16:38 UTC, Abenezer-Tilahun commented on index.html
> +          <h1 class="tonic-text">Multi-Post <br>
- [x] Kindly I recommend you to use a header tag `hx(h2)` for the the project title (e.g., "Multi-Post") instead of using `h1` tag for the purpose of search and optimization there must be only one `h1`   tag for your project.

2023-02-22 16:38 UTC, Abenezer-Tilahun commented on index.html
> +          <h1 class="tonic-text">Tonic</h1>
- [x] Kindly I recommend you to use a header tag `hx(h2)` for the the project title (e.g., "Tonic") instead of using `h1` tag for the purpose of search and optimization there must be only one `h1`   tag for your project.

2023-02-22 16:38 UTC, Abenezer-Tilahun commented on index.html
> +          <h1 class="tonic-text">Multi-Post <br>
- [x] Kindly I recommend you to use a header tag `hx(h2)` for the the project title (e.g., "Multi-Post") instead of using `h1` tag for the purpose of search and optimization there must be only one `h1`   tag for your project.

2023-02-22 16:38 UTC, Abenezer-Tilahun commented on index.html
> +              <h1 class="text_project">See Project</h1>
- [ ] Kindly I recommend you to use only `button` tag for the See Project , please remove the `h1` tag for all of the button tag.

2023-02-22 16:38 UTC, Abenezer-Tilahun commented on index.html
> +              <h1 class="text_project">See Project</h1>
- [x] Kindly I recommend you to use only `button` tag for the See Project , please remove the `h1` tag for all of the button tag.

2023-02-22 16:38 UTC, Abenezer-Tilahun commented on index.html
> +      <h2 class="connect">LET’S CONNECT</h2>
- [x] Kindly I recommend you to use `h3` tag for  other titles (e.g., "Let's connect"), instead of the using h2 tag for the purpose of the hierarchy.

2023-02-22 16:38 UTC, Abenezer-Tilahun commented on index.html
> +        <h1 class="text_project">See Project</h1>
- [x] Kindly I recommend you to use only `button` tag for the See Project , please remove the `h1` tag for all of the button tag.

2023-02-22 16:38 UTC, Abenezer-Tilahun commented on index.html
> +    </div>
- [ ] Kindly I recommend you to use `ul` tag for the technology in each category(e.g., "JavasScript", "HTML" and "CSS") and each of them a `li` tag  instead of the `div` tag .

2023-02-22 16:38 UTC, Abenezer-Tilahun commented on style.css
> +}
- [ ] Good job for implemented the the button interactions (enable, hover, etc.), but kindly i recommend you implement  button interaction just like the Figma design.

 
![Capture](https://user-images.githubusercontent.com/93598189/220694582-0140cf03-0c55-4d0b-84cb-d2647ef8cca4.PNG)

2023-02-22 22:07 UTC, joel-kalema approved these changes
Hi @coker2019 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![ ](https://media4.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif)
## Highlights
Linters are passing 👍 
The project is running successfully 👍 

## Optional suggestions

- [ ] [OPTIONAL] Good job implementing the mobile version, but you may try to fix as well the `background image` of your `home page` and the `margin` of the `button` to stick to the design as much as possible (e.g., font, colors, images, text, margins) using [the templates in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1) as it is [required](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/2_mobile.md#:~:text=You%20must%20stick%20to%20the%20design%20as%20much%20as%20possible%20(e.g.%2C%20font%2C%20colors%2C%20images%2C%20text%2C%20margins)%20using%20the%20templates%20in%20Figma.) 👍 .
> | | Figma template | | Your project | |
> |-|---------|-|--------|-|
> | |![mobile01](https://user-images.githubusercontent.com/57408419/220767740-1290c13b-a614-4b78-aa88-e1360e9b550b.jpg)| |![mobile](https://user-images.githubusercontent.com/57408419/220765218-5bd980af-05c6-4fef-9e01-dd80aa536363.jpg)| |






_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me **@joel-kalema** in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-22 23:31 UTC, merged

2023-03-21 12:05 UTC, ichala reviewed
Hi Student  ,
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:  
 
![68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f6c3366516333614356304871707a5763552f67697068792e676966](https://user-images.githubusercontent.com/85113567/184604589-430cf4bc-1d2e-4603-976a-7a48a899ea35.gif)

# To Highlight 💪🏻

- Project Already approved ✔️ 


 Good job implementing the requirements  :+1: Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Optional Suggestions  :

- N/A


**********
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag  ichala in your question so I can receive the notification.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._