Contact Section
coker2019/Coker_Portfolio pull request #4
Opened 2023-03-01 09:00 UTC by coker2019

Added  the contact section to my mobile first portfolio project.

2023-03-01 09:48 UTC, Lizdev-05 requested changes
Hi @coker2019, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media4.giphy.com/media/m3864rBwwBTKMAbpn3/giphy.gif"/>
## Highlights
- Correct GitHub Flow 👍

- Good commit history 💰

- Good PR title💯

- All linters passed 🏅

- Personalised README file 👍


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-01 09:48 UTC, Lizdev-05 commented on index.html
> +        </label>
Great job so far 👍 . Kindly make sure all the input field has the `required` attribute to activate the validation on submit. 😊

2023-03-01 09:48 UTC, Lizdev-05 commented on index.html
> +          <textarea class="message_box" name="message" placeholder="write your message here"></textarea>
According to the requirement, the message textarea should have a `max length of "500"` attribute. Kindly add it to it. 😊

2023-03-01 09:48 UTC, Lizdev-05 commented on index.html
> +            accept-charset="utf-30">
Great job so far, According to the requirement, the message input field for the name should have a max length of "300" attribute. Kindly implement it. 😊

2023-03-01 09:48 UTC, Lizdev-05 commented on index.html
> +      </form>
Kindly make sure the button interactions such as hover, active (when it's pressed), disabled and enable (default state) are styled as shown in the Figma template. 👇 

<img width="945" alt="image" src="https://user-images.githubusercontent.com/73854999/222103155-6d784305-0f56-4286-b128-1a43f2143d12.png">

2023-03-01 13:49 UTC, souad988 approved these changes
Hi @coker2019 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f6a4a5143327075565a70544d4f34765573302f67697068792e676966](https://user-images.githubusercontent.com/59707859/222157017-b4cb24f9-31a7-489b-a5c8-9579584c9b44.gif)


## Highlights
✔Good use of github workflow
✔Good PR title
✔No linter errors
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-01 15:14 UTC, merged

2023-03-28 09:52 UTC, Abenezer-Tilahun reviewed
Hi @coker2019 
 
Your project is complete  👍 💯   There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 👏🏻

✔️ No linter errors.
✔️ You used correct GitHub-Flow.
✔️ Professional README  
✔️ Good Commit Messages
✔️ Good job for Implemented Portfolio: add a contact form and finish the mobile version.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).